safe: true
markdown: kramdown
highlighter: pygments
permalink: /:title.html
relative_permalinks: false

default_theme: ribbon
default_width: 792
default_lang: en
default_body_class: list

author:
    name: JRowing
    url:  http://jrowing.com/
    company:
        name: IoP SPN.
        # url:  http://example.com/

fork_url: https://JRowing.com/woah
progress: true
line_numbers: true
